// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwgcChpbFz9CtjTEVpoGnJQfCa6dvlz-0',
    appId: '1:655484012129:android:391a7a3e0fc0607bfc0c20',
    messagingSenderId: '655484012129',
    projectId: 'borsatemettutakip',
    storageBucket: 'borsatemettutakip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa2_zSZPZdtXXiysIbOQx8B_Ru3hcZIn8',
    appId: '1:655484012129:ios:73823288eac5fec5fc0c20',
    messagingSenderId: '655484012129',
    projectId: 'borsatemettutakip',
    storageBucket: 'borsatemettutakip.appspot.com',
    androidClientId: '655484012129-0ek1t7aul4gm0rg9i6d1u1sbcr6e8jl4.apps.googleusercontent.com',
    iosClientId: '655484012129-51o1rmbcu8p1bp5n6gjgfa1q8ifb0gg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.halkaArzTemettu',
  );
}
